version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*" # Group all dependencies together in a single PR
    assignees:
      - tristanhollman
